name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: |
        # Certifique-se de que o nome do repositório está em letras minúsculas
        DOCKER_REPO=ghcr.io/weriqui/aninhazap

        # Limpe a variável github.ref para usá-la como tag
        TAG=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')

        docker build -t $DOCKER_REPO:$TAG -f Dockerfile .
        docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:latest
    
    - run: |
        # Faça o push das imagens
        DOCKER_REPO=ghcr.io/weriqui/aninhazap

        # Limpe a variável github.ref para usá-la como tag
        TAG=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')

        docker push $DOCKER_REPO:$TAG
        docker push $DOCKER_REPO:latest
